# Generated by Django 5.2.5 on 2025-08-24 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_manager", "0003_remove_subscription_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liability",
            name="date",
            field=models.DateField(default=datetime.date(2025, 8, 24)),
        ),
    ]
