# Generated by Django 5.2.5 on 2025-08-25 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_manager", "0005_alter_liability_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liability",
            name="date",
            field=models.DateField(default=datetime.date(2025, 8, 25)),
        ),
    ]
