# Generated by Django 5.2.5 on 2025-08-25 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_manager", "0006_alter_liability_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liability",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
